src/blog/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from blog import views

urlpatterns = patterns(
    '',
    url(r'^$',
        views.PostList.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<pk>\d+)/(?P<slug>[-\w]+)$',
        views.PostDetail.as_view(), name='post_detail'),
    url(r'^new-post$',
        login_required(views.PostCreate.as_view()), name='post_new'),
    url(r'^edit-post/(?P<pk>\d+)$',
        login_required(views.PostUpdate.as_view()), name='post_edit'),
    url(r'^delete-post/(?P<pk>\d+)$',
        login_required(views.PostDelete.as_view()), name='post_delete'),
    url(r'^about$',
        TemplateView.as_view(template_name="about.html"), name='about'),
    url(r'^archives$',
        views.Archives.as_view(), name='archives'),
)

src/urls.py
from django.conf.urls.defaults import url, patterns, include
import dbindexer

handler500 = 'djangotoolbox.errorviews.server_error'

# search for dbindexes.py in all INSTALLED_APPS and load them
dbindexer.autodiscover()

urlpatterns = patterns(
    '',
    url('^_ah/warmup$', 'djangoappengine.views.warmup'),
    url(r'^accounts/login/$',
        'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$',
        'django.contrib.auth.views.logout'),
    url(r'^', include('blog.urls', namespace='blog')),
)

src/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=300)
    body = models.TextField()
    slug = models.SlugField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, null=True, blank=True)

    class Meta:
        ordering = ["-pub_date"]

    def __unicode__(self):
        return self.title

src/blog/forms.py
from django import forms
from blog.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'body']

src/blog/views.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render_to_response
from django.template.defaultfilters import slugify
from django.views.generic import View, DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from blog.forms import PostForm
from blog.models import Post


class PostDetail(DetailView):
    model = Post


class PostList(ListView):
    model = Post
    paginate_by = 5


class PostCreate(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        return super(PostCreate, self).form_valid(form)


class PostUpdate(UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title)
        return super(PostUpdate, self).form_valid(form)


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')


class Archives(View):

    def get(self, request):
        posts = Post.objects.all().order_by('-pub_date')
        return render_to_response('archives.html', {'posts': posts})

src/blog/templates/about.html
{% extends "base.html" %}

{% block title %} - About{% endblock %}

{% block content %}
<h1>About</h1>

<p>Bacon ipsum dolor sit amet strip steak venison ham, andouille t-bone spare ribs short ribs bresaola shankle chicken. Flank tail tenderloin shoulder hamburger venison filet mignon kevin ham hock andouille shankle pork chop turducken rump meatloaf. Flank sausage t-bone, doner prosciutto pig turducken andouille salami tongue jowl ball tip sirloin tail. Pork jowl tri-tip hamburger frankfurter beef brisket cow ribeye. Capicola pig t-bone turkey chuck short loin sirloin ground round ham pork chop kevin brisket leberkas ball tip. Andouille beef ribs chicken boudin doner, biltong pork loin hamburger sirloin pancetta. Pancetta pork chop meatloaf sirloin ground round beef ball tip spare ribs pig.</p>

<p>Pig capicola shoulder t-bone kielbasa spare ribs tenderloin. Hamburger turkey swine kielbasa. Swine drumstick cow fatback rump. Shank capicola bacon jerky, frankfurter boudin pork chop. Short ribs pork chop short loin tri-tip flank brisket drumstick. Cow meatball tri-tip beef ribs pork, spare ribs frankfurter pork loin sirloin swine doner ground round salami pastrami.</p>

<p>Shoulder tongue venison ham hock turkey biltong drumstick chicken filet mignon meatball bacon. Chuck prosciutto jowl tri-tip, drumstick jerky tongue pastrami strip steak ground round rump bresaola salami. Pork loin tri-tip short ribs tongue shoulder capicola flank sausage prosciutto brisket pig andouille. Ham hock swine shankle, prosciutto cow shoulder brisket bacon leberkas sirloin fatback frankfurter ground round bresaola.</p>

<p>Leberkas jowl meatball filet mignon tongue turkey ground round capicola rump shoulder. Bacon kielbasa boudin pork belly hamburger. Drumstick pork belly short loin tri-tip, strip steak sirloin chicken biltong frankfurter salami. Jerky swine prosciutto fatback filet mignon brisket shoulder. Pastrami frankfurter t-bone, sausage tenderloin fatback biltong tongue swine capicola shank jowl prosciutto short loin.</p>

{% endblock content %}

src/blog/templates/archives.html
{% extends "base.html" %}

{% load url from future %}

{% block title %} - Archives{% endblock %}

{% block content %}
<h1>Archives</h1>

<div id="archives">
  <hr>
  {% regroup posts by pub_date|date:"Y" as year_list %}
  {% for year in year_list %}
      <h2>{{ year.grouper }}</h2>
      {% for post in year.list %}
        <article class="row">
          <time class="col-md-1" datetime="{{ post.pub_date|date:"U" }}">
            <span class="month">{{ post.pub_date|date:"b" }}</span>
            <span class="day">{{ post.pub_date|date:"d" }}</span>
          </time>
          <div class="col-md-9">
            <h1><a href="{% url 'blog:post_detail' year=post.pub_date.year month=post.pub_date.month pk=post.id slug=post.slug %}">{{ post.title }}</a></h1>
          </div>
        </article>
      {% endfor %}
      <hr style="margin-top: 5px;">
  {% endfor %}
</div>

{% endblock content %}

src/blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %} - Confirm deletion for {{ object.title }}{% endblock %}

{% block content %}
<h2>Confirm deletion for {{ object.title }}</h2>

  <form role="form" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object.title }}"?<p>
    <button type="submit" class="btn btn-default">Delete</button> 
  </form>

{% endblock %}

src/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% load url from future %}
{% load blog_extras %}

{% block content %}
  {% with post=object %}
  <article class="entry">
      <header>
        <h2><a href="{% url 'blog:post_detail' year=post.pub_date.year month=post.pub_date.month pk=post.id slug=post.slug %}">{{ post.title }}</a></h2>
        <h5>Posted {{ post.pub_date }} by {{ post.author }}</h5>
      </header>
      <div class="entry-content">
        {{ post.body|markdown }}
      </div>
      {% if user.is_authenticated %}
        <div class="btn-group btn-group-xs">
          <a class="btn btn-default" href="{% url 'blog:post_edit' post.id %}">Edit</a>
          <a class="btn btn-default" href="{% url 'blog:post_delete' post.id %}">Delete</a>
        </div>
      {% endif %}
    </article>
  <section class="comments">
    <div id="disqus_thread"></div>
      <script type="text/javascript">
          var disqus_shortname = 'app-engine-blog';

          (function() {
              var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
              dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
              (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
      <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
  </section>
  {% endwith %}
{% endblock %}

src/blog/templates/blog/post_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-default">Submit</button>
  </form>

{% endblock %}

src/blog/templates/blog/post_list.html
{% extends "base.html" %}

{% load url from future %}
{% load blog_extras %}

{% block content %}

  <div class="row">
    <div class="col-lg-9">
      {% for post in object_list %}
        <article class="entry">
          <header>
            <h2><a href="{% url 'blog:post_detail' year=post.pub_date.year month=post.pub_date.month pk=post.id slug=post.slug %}">{{ post.title }}</a></h2>
            <h5>Posted {{ post.pub_date }} by {{ post.author }}</h5>
          </header>
          <div class="entry-content">
            {{ post.body|markdown }}
          </div>
          {% if user.is_authenticated %}
            <div class="btn-group btn-group-xs">
              <a class="btn btn-default" href="{% url 'blog:post_edit' post.id %}">Edit</a>
              <a class="btn btn-default" href="{% url 'blog:post_delete' post.id %}">Delete</a>
            </div>
          {% endif %}
        </article>
      {% endfor %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}" class="prev">&lsaquo;&lsaquo; Previous</a></li>
        {% else %}
            <li class="disabled prev"><a href="#">&lsaquo;&lsaquo; Previous</a></li>
        {% endif %}
        {% for page in pages %}
            {% if page %}
                {% ifequal page page_obj.number %}
                    <li class="current page active"><a href="#">{{ page }}</a></li>
                {% else %}
                    <li><a href="?page={{ page }}" class="page">{{ page }}</a></li>
                {% endifequal %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="next">Next &rsaquo;&rsaquo;</a></li>
        {% else %}
            <li class="disabled next"><a href="#">Next &rsaquo;&rsaquo;</a></li>
        {% endif %}
      </ul>
    </div>
    <div class="col-lg-3">
      <div class="sidebar">
        <div class="sidebar-title">Recent Posts</div>
        <ul>
          {% for post in object_list|slice:":5" %}
            <li><a href="{% url 'blog:post_detail' year=post.pub_date.year month=post.pub_date.month pk=post.id slug=post.slug %}">{{ post.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/base.html
{% load url from future %}

<!DOCTYPE html>
<html>
  <head>
    <title>App Engine's blog {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/static/css/bootstrap-markdown.min.css">
    <link rel="stylesheet" href="/static/css/main.css">

  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">App Engine's blog</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
            <li><a href="{% url 'blog:about' %}">About</a></li>
            <li><a href="{% url 'blog:archives' %}">Archives</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'blog:post_new' %}">New post</a></li>
                  <li><a href="{% url 'django.contrib.auth.views.logout' %}?next={{request.path}}">Sign out</a></li>
                </ul>
              </li>
            {% else %}
              <li><a href="{% url 'django.contrib.auth.views.login' %}?next={{request.path}}">Sign in</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>

    <div class="container">

      <div id="content">
        {% block content %}{% endblock %}
      </div>

    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="/static/js/markdown.js"></script>
    <script src="/static/js/to-markdown.js"></script>
    <script src="/static/js/bootstrap-markdown.js"></script>
    <script src="/static/js/main.js"></script>
  </body>
</html>